version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.3
 # ansible: orbss/ansible-playbook@0.0.5
  #ruby: circleci/ruby@2.0.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cfn-execute:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: aws cloudformation deploy --template-file cloudformation/net --stack-name cfn-13-vpc
      - run: aws cloudformation deploy --template-file cloudformation/app --stack-name cfn-13-app
      - run: aws cloudformation deploy --template-file cloudformation/security --stack-name cfn-13-security
      #- run: aws cloudformation deploy --template-file cloudformation/04_elb.yml --stack-name cfn-lecture-elb
      #- run: aws cloudformation deploy --template-file cloudformation/05_s3.yml --stack-name cfn-lecture-s3

  

  #serverspec-execute:
   # docker:
    #  - image: cimg/ruby:2.7-node
    #steps:
     # - checkout
      #- run:
       #   name: Copy SSH Config
        #  command: cp sshconfig/config ~/.ssh/
      #- run:
       #   name: bundle install
        #  command: |
         #   cd serverspec
          #  gem list -e rails
           # bundle install --path vendor/bundle
      #- run:
          #name: execute
          #command: |
           # cd serverspec
           # bundle exec rake spec

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-execute:
          requires:
            - cfn-lint
      #- ansible-execute:
          #requires:
            - cfn-execute
      #- serverspec-execute:
          #requires:
           # - ansible-execute